DEFAULT_LANGUAGE = "fr"

LANGUAGES = {
    "fr": {"name": "Français", "rtl": False},
    "en": {"name": "English", "rtl": False},
    "ar": {"name": "العربية", "rtl": True},
    "zh": {"name": "中文", "rtl": False},
}

TRANSLATIONS = {
    "fr": {
        "about_app": "À propos de {app_name}",
        "about_description": "Application de bureau pour détecter, recadrer et imprimer uniquement la zone utile d'un bordereau PDF.",
        "about_license": "Licence",
        "about_license_text": "Licence du projet : <b>{license}</b><br>Les bibliothèques tierces restent soumises à leurs licences respectives.",
        "about_donation": "Dons",
        "about_credits": "Crédits techniques",
        "about_project": "Projet",
        "app_ready": "Ouvrez un PDF ou déposez-le dans l'aperçu.",
        "apply_all": "Appliquer à toutes",
        "apply_all_action": "Appliquer la zone à toutes les pages",
        "auto_detect": "Auto détecter",
        "all_pages": "Toutes les pages",
        "black_white": "Noir et blanc",
        "check_updates": "Vérifier les mises à jour",
        "color": "Couleur",
        "copies": "Copies",
        "current_page": "Page courante",
        "crop_draw_hint": "Cliquez-glissez hors du cadre pour dessiner une zone. Faites glisser un bord ou un coin pour l’ajuster.",
        "detect_failed": "Détection impossible",
        "detected": "Zones détectées automatiquement.",
        "duplex": "Recto-verso",
        "duplex_default": "Défaut de l'imprimante",
        "duplex_long": "Recto-verso bord long",
        "duplex_none": "Recto simple",
        "duplex_short": "Recto-verso bord court",
        "download_update": "Télécharger",
        "empty_preview": "Aucune zone détectée à imprimer.",
        "empty_pdf": "PDF vide",
        "empty_pdf_message": "Ce PDF ne contient aucune page.",
        "empty_pdf_status": "PDF vide.",
        "export": "Exporter cropped",
        "export_title": "Enregistrer le PDF recadré",
        "exported_status": "PDF recadré enregistré : {path}",
        "file_menu": "Fichier",
        "fit": "Ajuster",
        "fit_to_page": "Adapter à la page",
        "help_menu": "Aide",
        "light_theme": "Thème clair",
        "margin": "Marge",
        "menu_tools": "Outils",
        "menu_view": "Affichage",
        "menu_settings": "Paramètres…",
        "no_printer": "Aucune imprimante détectée",
        "open": "Ouvrir PDF",
        "open_failed": "Ouverture impossible",
        "opened_status": "PDF ouvert : {name}",
        "orientation": "Orientation",
        "orientation_auto": "Auto",
        "orientation_default": "Défaut",
        "orientation_landscape": "Paysage",
        "orientation_portrait": "Portrait",
        "page": "Page",
        "paper_size": "Format papier",
        "password_pdf": "PDF protégé",
        "password_pdf_message": "Ce PDF est protégé par mot de passe. L'ouverture n'est pas encore prise en charge.",
        "password_pdf_status": "PDF protégé par mot de passe.",
        "preview_error": "Impossible de générer l'aperçu :\n{error}",
        "preview_page": "Aperçu page",
        "print": "Imprimer",
        "print_failed": "Impression impossible",
        "print_failed_start": "Impossible de démarrer l'impression avec cette imprimante.",
        "print_no_pages": "Aucune page n'a pu être dessinée pour l'impression.",
        "print_no_pages_status": "Aucune page imprimable générée.",
        "print_options": "Options d'impression",
        "print_refused": "Impression refusée",
        "print_refused_message": "Le pilote d'imprimante a refusé le travail. Vérifiez que le format papier sélectionné correspond au rouleau/étiquette installé.",
        "print_refused_status": "Impression refusée par le pilote.",
        "print_status": "Travail transmis au système d'impression.",
        "print_title": "Imprimer la zone sélectionnée",
        "printer": "Imprimante",
        "printer_default": "Défaut de l'imprimante",
        "quality": "Qualité",
        "quality_draft": "Brouillon — 150 dpi",
        "quality_high": "Haute qualité — 600 dpi",
        "quality_standard": "Standard — 300 dpi",
        "quit": "Quitter",
        "settings": "Paramètres",
        "settings_language": "Langue",
        "settings_note": "Les paramètres sont enregistrés et appliqués immédiatement.",
        "sponsor_kofi": "Sponsoriser sur Ko-fi",
        "theme": "Thème",
        "theme_dark": "Thème sombre",
        "theme_light": "Thème clair",
        "update_check_failed": "Vérification impossible",
        "update_check_failed_message": "Impossible de vérifier les mises à jour pour le moment.",
        "update_checking": "Vérification des mises à jour...",
        "update_available": "Mise à jour disponible",
        "update_available_message": "Une nouvelle version de {app_name} est disponible.\n\nVersion installée : {current_version}\nNouvelle version : {latest_version}\n\nVoulez-vous ouvrir la page de téléchargement ?",
        "update_current": "Application à jour",
        "update_current_message": "{app_name} est déjà à jour.\n\nVersion installée : {current_version}",
        "update_later": "Plus tard",
        "toolbar_detection": "Détection",
        "toolbar_file": "Fichier",
        "toolbar_output": "Sortie",
        "toolbar_page": "Page",
        "toolbar_view": "Vue",
        "view_fit": "Ajuster à la fenêtre",
        "view_next": "Page suivante",
        "view_previous": "Page précédente",
        "zoom": "Zoom",
        "zoom_in": "Zoom avant",
        "zoom_out": "Zoom arrière",
        "zone_all_status": "Zone courante appliquée à toutes les pages.",
        "zone_fixed_status": "Zone corrigée pour la page courante.",
    },
    "en": {
        "about_app": "About {app_name}",
        "about_description": "Desktop app to detect, crop, and print only the useful area of a PDF shipping label.",
        "about_license": "License",
        "about_license_text": "Project license: <b>{license}</b><br>Third-party libraries remain subject to their own licenses.",
        "about_donation": "Donations",
        "about_credits": "Technical credits",
        "about_project": "Project",
        "app_ready": "Open a PDF or drop it in the preview.",
        "apply_all": "Apply to all",
        "apply_all_action": "Apply current area to all pages",
        "auto_detect": "Auto detect",
        "all_pages": "All pages",
        "black_white": "Black and white",
        "check_updates": "Check for updates",
        "color": "Color",
        "copies": "Copies",
        "current_page": "Current page",
        "crop_draw_hint": "Click and drag outside the frame to draw an area. Drag an edge or corner to adjust it.",
        "detect_failed": "Detection failed",
        "detected": "Areas detected automatically.",
        "duplex": "Duplex",
        "duplex_default": "Printer default",
        "duplex_long": "Duplex long edge",
        "duplex_none": "Simplex",
        "duplex_short": "Duplex short edge",
        "download_update": "Download",
        "empty_preview": "No detected area to print.",
        "empty_pdf": "Empty PDF",
        "empty_pdf_message": "This PDF does not contain any pages.",
        "empty_pdf_status": "Empty PDF.",
        "export": "Export cropped",
        "export_title": "Save cropped PDF",
        "exported_status": "Cropped PDF saved: {path}",
        "file_menu": "File",
        "fit": "Fit",
        "fit_to_page": "Fit to page",
        "help_menu": "Help",
        "light_theme": "Light theme",
        "margin": "Margin",
        "menu_tools": "Tools",
        "menu_view": "View",
        "menu_settings": "Settings…",
        "no_printer": "No printer detected",
        "open": "Open PDF",
        "open_failed": "Unable to open",
        "opened_status": "PDF opened: {name}",
        "orientation": "Orientation",
        "orientation_auto": "Auto",
        "orientation_default": "Default",
        "orientation_landscape": "Landscape",
        "orientation_portrait": "Portrait",
        "page": "Page",
        "paper_size": "Paper size",
        "password_pdf": "Protected PDF",
        "password_pdf_message": "This PDF is password protected. Opening it is not supported yet.",
        "password_pdf_status": "Password-protected PDF.",
        "preview_error": "Unable to generate preview:\n{error}",
        "preview_page": "Preview page",
        "print": "Print",
        "print_failed": "Print failed",
        "print_failed_start": "Unable to start printing with this printer.",
        "print_no_pages": "No page could be drawn for printing.",
        "print_no_pages_status": "No printable page generated.",
        "print_options": "Print options",
        "print_refused": "Print refused",
        "print_refused_message": "The printer driver refused the job. Check that the selected paper size matches the installed roll or label.",
        "print_refused_status": "Print refused by the driver.",
        "print_status": "Job sent to the print system.",
        "print_title": "Print selected area",
        "printer": "Printer",
        "printer_default": "Printer default",
        "quality": "Quality",
        "quality_draft": "Draft — 150 dpi",
        "quality_high": "High quality — 600 dpi",
        "quality_standard": "Standard — 300 dpi",
        "quit": "Quit",
        "settings": "Settings",
        "settings_language": "Language",
        "settings_note": "Settings are saved and applied immediately.",
        "sponsor_kofi": "Sponsor on Ko-fi",
        "theme": "Theme",
        "theme_dark": "Dark theme",
        "theme_light": "Light theme",
        "update_check_failed": "Update check failed",
        "update_check_failed_message": "Unable to check for updates right now.",
        "update_checking": "Checking for updates...",
        "update_available": "Update available",
        "update_available_message": "A new version of {app_name} is available.\n\nInstalled version: {current_version}\nNew version: {latest_version}\n\nDo you want to open the download page?",
        "update_current": "Application is up to date",
        "update_current_message": "{app_name} is already up to date.\n\nInstalled version: {current_version}",
        "update_later": "Later",
        "toolbar_detection": "Detection",
        "toolbar_file": "File",
        "toolbar_output": "Output",
        "toolbar_page": "Page",
        "toolbar_view": "View",
        "view_fit": "Fit to window",
        "view_next": "Next page",
        "view_previous": "Previous page",
        "zoom": "Zoom",
        "zoom_in": "Zoom in",
        "zoom_out": "Zoom out",
        "zone_all_status": "Current area applied to all pages.",
        "zone_fixed_status": "Area adjusted for the current page.",
    },
    "ar": {
        "about_app": "حول {app_name}",
        "about_description": "تطبيق سطح مكتب لاكتشاف واقتصاص وطباعة المنطقة المفيدة فقط من ملف PDF الخاص بملصق الشحن.",
        "about_license": "الترخيص",
        "about_license_text": "ترخيص المشروع: <b>{license}</b><br>تبقى المكتبات الخارجية خاضعة لتراخيصها الخاصة.",
        "about_donation": "الدعم",
        "about_credits": "الاعتمادات التقنية",
        "about_project": "المشروع",
        "app_ready": "افتح ملف PDF أو أسقطه في المعاينة.",
        "apply_all": "تطبيق على الكل",
        "apply_all_action": "تطبيق المنطقة الحالية على كل الصفحات",
        "auto_detect": "اكتشاف تلقائي",
        "all_pages": "كل الصفحات",
        "black_white": "أبيض وأسود",
        "check_updates": "التحقق من التحديثات",
        "color": "اللون",
        "copies": "النسخ",
        "current_page": "الصفحة الحالية",
        "crop_draw_hint": "انقر واسحب خارج الإطار لرسم منطقة. اسحب حافة أو زاوية لضبطها.",
        "detect_failed": "تعذر الاكتشاف",
        "detected": "تم اكتشاف المناطق تلقائياً.",
        "duplex": "طباعة مزدوجة",
        "duplex_default": "افتراضي الطابعة",
        "duplex_long": "مزدوج على الحافة الطويلة",
        "duplex_none": "وجه واحد",
        "duplex_short": "مزدوج على الحافة القصيرة",
        "download_update": "تنزيل",
        "empty_preview": "لا توجد منطقة مكتشفة للطباعة.",
        "empty_pdf": "ملف PDF فارغ",
        "empty_pdf_message": "لا يحتوي ملف PDF هذا على أي صفحات.",
        "empty_pdf_status": "ملف PDF فارغ.",
        "export": "تصدير المقصوص",
        "export_title": "حفظ PDF المقصوص",
        "exported_status": "تم حفظ PDF المقصوص: {path}",
        "file_menu": "ملف",
        "fit": "ملاءمة",
        "fit_to_page": "ملاءمة الصفحة",
        "help_menu": "مساعدة",
        "light_theme": "مظهر فاتح",
        "margin": "الهامش",
        "menu_tools": "الأدوات",
        "menu_view": "العرض",
        "menu_settings": "الإعدادات…",
        "no_printer": "لم يتم العثور على طابعة",
        "open": "فتح PDF",
        "open_failed": "تعذر الفتح",
        "opened_status": "تم فتح PDF: {name}",
        "orientation": "الاتجاه",
        "orientation_auto": "تلقائي",
        "orientation_default": "افتراضي",
        "orientation_landscape": "أفقي",
        "orientation_portrait": "عمودي",
        "page": "الصفحة",
        "paper_size": "حجم الورق",
        "password_pdf": "PDF محمي",
        "password_pdf_message": "ملف PDF هذا محمي بكلمة مرور. الفتح غير مدعوم حالياً.",
        "password_pdf_status": "PDF محمي بكلمة مرور.",
        "preview_error": "تعذر إنشاء المعاينة:\n{error}",
        "preview_page": "صفحة المعاينة",
        "print": "طباعة",
        "print_failed": "تعذرت الطباعة",
        "print_failed_start": "تعذر بدء الطباعة بهذه الطابعة.",
        "print_no_pages": "تعذر رسم أي صفحة للطباعة.",
        "print_no_pages_status": "لم يتم إنشاء صفحة قابلة للطباعة.",
        "print_options": "خيارات الطباعة",
        "print_refused": "رفضت الطباعة",
        "print_refused_message": "رفض برنامج تشغيل الطابعة المهمة. تحقق من أن حجم الورق المحدد يطابق اللفة أو الملصق المثبت.",
        "print_refused_status": "رفض برنامج التشغيل الطباعة.",
        "print_status": "تم إرسال المهمة إلى نظام الطباعة.",
        "print_title": "طباعة المنطقة المحددة",
        "printer": "الطابعة",
        "printer_default": "افتراضي الطابعة",
        "quality": "الجودة",
        "quality_draft": "مسودة — 150 dpi",
        "quality_high": "جودة عالية — 600 dpi",
        "quality_standard": "قياسي — 300 dpi",
        "quit": "خروج",
        "settings": "الإعدادات",
        "settings_language": "اللغة",
        "settings_note": "يتم حفظ الإعدادات وتطبيقها فوراً.",
        "sponsor_kofi": "ادعم عبر Ko-fi",
        "theme": "المظهر",
        "theme_dark": "مظهر داكن",
        "theme_light": "مظهر فاتح",
        "update_check_failed": "تعذر التحقق من التحديث",
        "update_check_failed_message": "لا يمكن التحقق من التحديثات حالياً.",
        "update_checking": "جارٍ التحقق من التحديثات...",
        "update_available": "يتوفر تحديث",
        "update_available_message": "يتوفر إصدار جديد من {app_name}.\n\nالإصدار المثبت: {current_version}\nالإصدار الجديد: {latest_version}\n\nهل تريد فتح صفحة التنزيل؟",
        "update_current": "التطبيق محدث",
        "update_current_message": "{app_name} محدث بالفعل.\n\nالإصدار المثبت: {current_version}",
        "update_later": "لاحقاً",
        "toolbar_detection": "الاكتشاف",
        "toolbar_file": "ملف",
        "toolbar_output": "الإخراج",
        "toolbar_page": "الصفحة",
        "toolbar_view": "العرض",
        "view_fit": "ملاءمة النافذة",
        "view_next": "الصفحة التالية",
        "view_previous": "الصفحة السابقة",
        "zoom": "تكبير",
        "zoom_in": "تكبير",
        "zoom_out": "تصغير",
        "zone_all_status": "تم تطبيق المنطقة الحالية على كل الصفحات.",
        "zone_fixed_status": "تم تعديل المنطقة للصفحة الحالية.",
    },
    "zh": {
        "about_app": "关于 {app_name}",
        "about_description": "用于检测、裁剪并只打印 PDF 运单有效区域的桌面应用。",
        "about_license": "许可证",
        "about_license_text": "项目许可证：<b>{license}</b><br>第三方库仍遵循各自的许可证。",
        "about_donation": "捐赠",
        "about_credits": "技术鸣谢",
        "about_project": "项目",
        "app_ready": "打开 PDF，或将它拖放到预览区。",
        "apply_all": "应用到全部",
        "apply_all_action": "将当前区域应用到所有页面",
        "auto_detect": "自动检测",
        "all_pages": "所有页面",
        "black_white": "黑白",
        "check_updates": "检查更新",
        "color": "颜色",
        "copies": "份数",
        "current_page": "当前页",
        "crop_draw_hint": "在框外单击并拖动以绘制区域。拖动边缘或角点进行调整。",
        "detect_failed": "检测失败",
        "detected": "已自动检测区域。",
        "duplex": "双面",
        "duplex_default": "打印机默认",
        "duplex_long": "长边双面",
        "duplex_none": "单面",
        "duplex_short": "短边双面",
        "download_update": "下载",
        "empty_preview": "没有可打印的检测区域。",
        "empty_pdf": "空 PDF",
        "empty_pdf_message": "此 PDF 不包含任何页面。",
        "empty_pdf_status": "空 PDF。",
        "export": "导出裁剪 PDF",
        "export_title": "保存裁剪后的 PDF",
        "exported_status": "裁剪后的 PDF 已保存：{path}",
        "file_menu": "文件",
        "fit": "适应",
        "fit_to_page": "适应页面",
        "help_menu": "帮助",
        "light_theme": "浅色主题",
        "margin": "边距",
        "menu_tools": "工具",
        "menu_view": "视图",
        "menu_settings": "设置…",
        "no_printer": "未检测到打印机",
        "open": "打开 PDF",
        "open_failed": "无法打开",
        "opened_status": "PDF 已打开：{name}",
        "orientation": "方向",
        "orientation_auto": "自动",
        "orientation_default": "默认",
        "orientation_landscape": "横向",
        "orientation_portrait": "纵向",
        "page": "页面",
        "paper_size": "纸张大小",
        "password_pdf": "受保护的 PDF",
        "password_pdf_message": "此 PDF 受密码保护，暂不支持打开。",
        "password_pdf_status": "受密码保护的 PDF。",
        "preview_error": "无法生成预览：\n{error}",
        "preview_page": "预览页",
        "print": "打印",
        "print_failed": "打印失败",
        "print_failed_start": "无法使用此打印机开始打印。",
        "print_no_pages": "没有页面可用于打印。",
        "print_no_pages_status": "未生成可打印页面。",
        "print_options": "打印选项",
        "print_refused": "打印被拒绝",
        "print_refused_message": "打印机驱动拒绝了任务。请检查所选纸张大小是否匹配已安装的纸卷或标签。",
        "print_refused_status": "驱动拒绝打印。",
        "print_status": "任务已发送到打印系统。",
        "print_title": "打印所选区域",
        "printer": "打印机",
        "printer_default": "打印机默认",
        "quality": "质量",
        "quality_draft": "草稿 — 150 dpi",
        "quality_high": "高质量 — 600 dpi",
        "quality_standard": "标准 — 300 dpi",
        "quit": "退出",
        "settings": "设置",
        "settings_language": "语言",
        "settings_note": "设置会保存并立即应用。",
        "sponsor_kofi": "在 Ko-fi 上赞助",
        "theme": "主题",
        "theme_dark": "深色主题",
        "theme_light": "浅色主题",
        "update_check_failed": "无法检查更新",
        "update_check_failed_message": "目前无法检查更新。",
        "update_checking": "正在检查更新...",
        "update_available": "有可用更新",
        "update_available_message": "{app_name} 有新版本可用。\n\n已安装版本：{current_version}\n新版本：{latest_version}\n\n是否打开下载页面？",
        "update_current": "应用已是最新",
        "update_current_message": "{app_name} 已是最新版本。\n\n已安装版本：{current_version}",
        "update_later": "稍后",
        "toolbar_detection": "检测",
        "toolbar_file": "文件",
        "toolbar_output": "输出",
        "toolbar_page": "页面",
        "toolbar_view": "视图",
        "view_fit": "适应窗口",
        "view_next": "下一页",
        "view_previous": "上一页",
        "zoom": "缩放",
        "zoom_in": "放大",
        "zoom_out": "缩小",
        "zone_all_status": "当前区域已应用到所有页面。",
        "zone_fixed_status": "已调整当前页面区域。",
    },
}


def is_rtl(language: str) -> bool:
    return LANGUAGES.get(language, LANGUAGES[DEFAULT_LANGUAGE])["rtl"]


def language_name(language: str) -> str:
    return LANGUAGES.get(language, LANGUAGES[DEFAULT_LANGUAGE])["name"]


def translate(language: str, key: str, **values: object) -> str:
    catalog = TRANSLATIONS.get(language, TRANSLATIONS[DEFAULT_LANGUAGE])
    text = catalog.get(key, TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key))
    return text.format(**values) if values else text
